name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  docker-build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: agent:latest
